language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t davidcdorbecker/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true davidcdorbecker/docker-react npm run test